const productList = [
  {
    id: 1,
    name: "Waffle with Berries",
    type: "Waffle",
    price: 6.5,
    imgMobile: "/assets/images/image-waffle-mobile.jpg",
    imgThumbnail: "/assets/images/image-waffle-thumbnail.jpg",

  },
  {
    id: 2,
    name: "Vanilla Bean Crème Brûlée",
    type: "Crème Brûlée",
    price: 7.0,
    imgMobile: "/assets/images/image-creme-brulee-mobile.jpg",
    imgThumbnail: "/assets/images/image-creme-brulee-thumbnail.jpg",
  },
  {
    id: 3,
    name: "Macaron Mix of Five",
    type: "Macaron",
    price: 8.0,
    imgMobile: "/assets/images/image-macaron-mobile.jpg",
    imgThumbnail: "/assets/images/image-macaron-thumbnail.jpg",
  },
  {
    id: 4,
    name: "Classic Tiramisu",
    type: "Tiramisu",
    price: 5.5,
    imgMobile: "/assets/images/image-tiramisu-mobile.jpg",
    imgThumbnail: "/assets/images/image-tiramisu-thumbnail.jpg",
  },
  {
    id: 5,
    name: "Pistachio Baklava",
    type: "Baklava",
    price: 4.0,
    imgMobile: "/assets/images/image-baklava-mobile.jpg",
    imgThumbnail: "/assets/images/image-baklava-thumbnail.jpg",
  },
  {
    id: 6,
    name: "Lemon Meringue Pie",
    type: "Pie",
    price: 5.0,
    imgMobile: "/assets/images/image-meringue-mobile.jpg",
    imgThumbnail: "/assets/images/image-meringue-thumbnail.jpg",
  },
  {
    id: 7,
    name: "Red Velvet Cake",
    type: "Cake",
    price: 4.5,
    imgMobile: "/assets/images/image-cake-mobile.jpg",
    imgThumbnail: "/assets/images/image-cake-thumbnail.jpg",
  },
  {
    id: 8,
    name: "Salted Caramel Brownie",
    type: "Brownie",
    price: 4.5,
    imgMobile: "/assets/images/image-brownie-mobile.jpg",
    imgThumbnail: "/assets/images/image-brownie-thumbnail.jpg",
  },
  {
    id: 9,
    name: "Vanilla Panna Cotta",
    type: "Panna Cotta",
    price: 6.5,
    imgMobile: "/assets/images/image-panna-cotta-mobile.jpg",
    imgThumbnail: "/assets/images/image-panna-cotta-thumbnail.jpg",
  },
];
export default productList;
